name: edbook
channels:
  - conda-forge
  - defaults
dependencies:
  - pypandoc=1.5
  - sphinx=6.1
  - python=3.10
  - typer=0.4.1
  - sphinx-rtd-theme=1.2.0
  - sphinxcontrib-youtube
  - pyyaml=6.0
  - coloredlogs=15.0.1
  - jinja2=3.1.2
  - sphinx-autobuild=2021.3.14
  - sphinx-togglebutton=0.3.2
  - pip=23.0.1
  - pip:
    - sphinxcontrib-katex==0.9.4
    - sphinxcontrib-custombutton @ https://github.com/edbook/sphinxcontrib-custombutton/archive/refs/tags/v2.0.zip
    - sphinxcontrib-datacamp @ https://github.com/edbook/sphinxcontrib-datacamp/archive/refs/tags/v2.0.zip
    - sphinxcontrib-geogebra @ https://github.com/edbook/sphinxcontrib-geogebra/archive/refs/tags/v2.0.zip
    - sphinxcontrib-hoverrole @ https://github.com/edbook/sphinxcontrib-hoverrole/archive/refs/tags/v2.0.6.zip
    - sphinxcontrib-panopto @ https://github.com/edbook/sphinxcontrib-panopto/archive/refs/tags/v2.0.zip
    - sphinxcontrib-questionnaire @ https://github.com/edbook/sphinxcontrib-questionnaire/archive/refs/tags/v2.0.9.zip
    - sphinxcontrib-sagecell @ https://github.com/edbook/sphinxcontrib-sagecell/archive/refs/tags/v2.0.zip
    - sphinxcontrib-scrolldepth @ https://github.com/edbook/sphinxcontrib-scrolldepth/archive/refs/tags/v2.0.zip
      #     - sphinxcontrib-toggleblock @ https://github.com/edbook/sphinxcontrib-toggleblock/archive/refs/tags/v2.0.zip
